const ERROR = {
  CREDENTIALS_INVALID : '이메일 또는 비밀번호가 틀렸습니다.',
  AUTH_REQUIRED: '로그인이 필요합니다',
  USER_NOT_FOUND : '사용자를 찾을 수 없습니다',
  FILE_UPLOAD_FAILED : '파일 업로드에 실패했습니다',
  POST_NOT_FOUND : '게시글을 찾을 수 없습니다.',
  INVALID_VALUE : '유효하지 않은 값입니다.',
  USERNAME_INVALID: '한글로 이름을 입력해주세요.',
  USERNAME_REQUIRED: '이름은 필수 입력사항입니다.',
  PASSWORD_REQUIRED: '비밀번호를 입력해주세요.',
  PASSWORD_INVALID: '비밀번호가 올바르지 않습니다.',
  ORDER_ITEMS_REQUIRED: '선택된 주문 상품이 없습니다.',
  ORDER_NOT_FOUND: '해당 주문을 찾을 수 없습니다.',
  CATEGORY_NOT_FOUND: '카테고리를 찾을 수 없습니다.',
  EMAIL_NOT_FOUND: '등록되지 않은 이메일입니다.',
  EMAIL_DUPLICATE: '이미 등록된 이메일입니다.',
  CATEGORY_REQUIRED: '소분류 카테고리가 선택되지 않았습니다.',
  PHONE_INVALID: '전화번호 양식이 올바르지 않습니다.',
  DUPLICATE_CATEGORY: '이미 존재하는 카테고리입니다.',
  ADDREDD_PHONE_REQUIRED: '배송지와 전화번호를 모두 입력해주세요.',
  PRODUCT_NOT_FOUND: '등록되지 않은 상품입니다.',
  AGREEMENT_REQUIRED: '동의 사항을 모두 체크해주세요',
  INTERNAL_ERROR: '서버 오류가 발생했습니다.',
  REQUEST_FAILED: '요청에 실패했습니다.',
  ADMIN_DELETE_NOT_ALLOWED: '관리자 계정은 삭제할 수 없습니다.',
};

module.exports = { ERROR };
